import shirt from "@/src/assets/product/tshirt.jpg"
import shirt2 from "@/src/assets/product/tshirt2.jpg"
import shirt3 from "@/src/assets/product/tshirt3.jpg"
import shirt4 from "@/src/assets/product/tshirt4.jpg"
import shirt5 from "@/src/assets/product/tshirt5.jpeg"
import shirt6 from "@/src/assets/product/tshirt6.jpg"
import shirt7 from "@/src/assets/product/tshirt7.jpg"
import shirt8 from "@/src/assets/product/tshirt8.jpeg"
import shirt9 from "@/src/assets/product/tshirt9.jpg"
import shirt10 from "@/src/assets/product/tshirt10.jpg"
import shirt11 from "@/src/assets/product/tshirt11.jpg"
import shirt12 from "@/src/assets/product/tshirt12.jpg"
import shirt13 from "@/src/assets/product/tshirt13.jpg"
import shirt14 from "@/src/assets/product/tshirt14.jpg"
import shirt15 from "@/src/assets/product/tshirt15.jpg"
import shirt16 from "@/src/assets/product/tshirt16.jpg"
import shirt17 from "@/src/assets/product/tshirt17.jpg"
import shirt18 from "@/src/assets/product/tshirt18.jpg"
import shirt19 from "@/src/assets/product/tshirt19.jpg"
import shirt20 from "@/src/assets/product/tshirt20.png"

export const productList = [
  {
    id: 1,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      shirt,
      shirt2,
      shirt3,
      shirt4,
    ],
    availability: "In Stock",
    rating: 4.5,
    color: "red",
    discount: 120,
    price: 3500,
    mrpPrice: 4201,
    category: "Handbags",
    thumbelImage: shirt,
    label: "",
    code: "ZARGANZ123",
    video: "https://youtube.com/shorts/MetexKsZcEU?si=lDLVfVKlbr8O1qOs",
  },
  {
    id: 2,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    color: "blue",
    price: 500,
    mrpPrice: 600,
    discount: "",
    category: "watches",
    label: "",
    code: "ZARGANZ2045",
    thumbelImage: shirt2,
    video: "https://youtube.com/shorts/VqYODsyv9e4?si=0T_b6qcvxyWmFnqg",
  },
  {
    id: 3,
    title: "Travel Leather Backpack",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "black",
    price: 350,
    mrpPrice: 400,
    discount: "",
    category: "Shoes",
    label: "",
    code: "WEBSE2045",
    thumbelImage: shirt3,
    video: "https://youtube.com/shorts/eHQ1stu0cu0?si=DYxw1CcBDWafXsYI",
  },
  {
    id: 4,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "green",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "Perfume",
    thumbelImage: shirt4,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
  {
    id: 5,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "purple",
    price: 3500,
    mrpPrice: "",
    discount: "",
    category: "Handbags",
    label: "box packaging",
    code: "YAAS2045",
    thumbelImage: shirt5,
    video: "https://youtube.com/shorts/FCepKLOM5A4?si=dVYFTVCPRa3eQBvk",
  },
  {
    id: 6,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "yellow",
    price: 1280,
    mrpPrice: "",
    category: "Perfume",
    discount: 80,
    thumbelImage: shirt6,
    label: "",
    code: "QEAS2045",
    video: "https://youtube.com/shorts/9JsTj1Ymi_I?si=IIlbA6RzbAtHVNLk",
  },
  {
    id: 7,
    title: "iPhone 8 Plus 64GB Full Color",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    color:  "pink",
    price: 620,
    mrpPrice: 700,
    discount: "",
    category: "watches",
    label: "new arrival",
    code: "XXEAS2045",
    thumbelImage: shirt7,
    video: "https://youtube.com/shorts/zVmYExoOhko?si=3AK98GRMAyZR03ZS",
  },
  {
    id: 8,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    color: "red",
    discount: 120,
    price: 3500,
    mrpPrice: 4201,
    category: "Handbags",
    thumbelImage: shirt8,
    label: "",
    code: "ZARGANZ123",
    video: "https://youtube.com/shorts/MetexKsZcEU?si=lDLVfVKlbr8O1qOs",
  },

  {
    id: 9,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    color: "black",
    discount: 120,
    price: 3500,
    mrpPrice: 4201,
    category: "Handbags",
    thumbelImage: shirt9,
    label: "",
    code: "ZARGANZ123",
    video: "https://youtube.com/shorts/MetexKsZcEU?si=lDLVfVKlbr8O1qOs",
  },
  {
    id: 10,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    color: "blue",
    price: 500,
    mrpPrice: 600,
    discount: "",
    category: "watches",
    label: "",
    code: "ZARGANZ2045",
    thumbelImage: shirt10,
    video: "https://youtube.com/shorts/VqYODsyv9e4?si=0T_b6qcvxyWmFnqg",
  },
  {
    id: 11,
    title: "Zara Women Leather Bag",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    availability: "In Stock",
    rating: 4.5,
    color: "green", 
    price: 500,
    mrpPrice: 600,
    discount: "",
    category: "watches",
    label: "",
    code: "ZARGANZ2045",
    thumbelImage: shirt11,
    video: "https://youtube.com/shorts/VqYODsyv9e4?si=0T_b6qcvxyWmFnqg",
  },
  {
    id: 12,
    title: "Travel Leather Backpack",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "black",
    price: 350,
    mrpPrice: 400,
    discount: "",
    category: "Shoes",
    label: "",
    code: "WEBSE2045",
    thumbelImage: shirt12,
    video: "https://youtube.com/shorts/eHQ1stu0cu0?si=DYxw1CcBDWafXsYI",
  },

  {
    id: 13,
    title: "Travel Leather Backpack",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "Out of Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color:  "blue",
    price: 350,
    mrpPrice: 400,
    discount: "",
    category: "Shoes",
    label: "",
    code: "WEBSE2045",
    thumbelImage: shirt13,
    video: "https://youtube.com/shorts/eHQ1stu0cu0?si=DYxw1CcBDWafXsYI",
  },
  {
    id: 14,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color:  "pink",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "Perfume",
    thumbelImage: shirt14,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
  {
    id: 17,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "yellow",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "Perfume",
    thumbelImage: shirt15,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
  {
    id: 15,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "yellow",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "tote bags",
    thumbelImage: shirt16,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
  {
    id: 18,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "blue",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "sale",
    thumbelImage: shirt18,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
  {
    id: 16,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "blue",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "sale",
    thumbelImage: shirt17,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
  {
    id: 19,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "blue",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "sale",
    thumbelImage: shirt19,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
  {
    id: 20,
    title: "PRODUCT NAME HERE",
    description: "This is a sample product description.",
    details: "These are the detailed specifications of the product.",
    availability: "In Stock",
    images: [
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
      "https://i.ibb.co.com/WpWqWgV9/perfectP.png",
    ],
    rating: 4.5,
    color: "blue",
    price: 7580,
    mrpPrice: 8000,
    discount: 200,
    category: "sale",
    thumbelImage: shirt20,
    label: "",
    code: "TSSE2045",
    video: "https://youtube.com/shorts/eNNMef6yrEM?si=n8x_p5_5GY8ZwXG3",
  },
];
